# Аккаунты для проверки выхода новых подарков
sessions_for_checking = ["account1"]

# Задержки
sleep_checking_seconds = 1      # Задержка между циклами проверки новых подарков

# Режимы
is_test_mode = false            # Режим, чтобы протестировать работу, программа будет думать, как будто имеется 2 доступных подарка для покупки
test_mode_max_balance = 15      # В тестовом режиме бот будет думать, что имеется указанное кол-во звезд на балансе, дабы не тратить полный баланс на тест
is_infinite_buying = true       # В данном режмие после покупки программа продолжит проверять новые подарки и закупать. Не работает в тестовом режиме, во избежание полного списания баланса

# Конфигурация отправки подарков
[[send_config]]
session_name_send_from = "account1" # Аккаунт со звёздами (Имя сессии)
username_send_to = "@someuser1"     # Получатель подарков: аккаунт или канал

#[[send_config]]
#session_name_send_from = "account2"
#username_send_to = "@someuser2"

# Фильтры подарков - белый список (по умолчанию будет покупать все лимитированные подарки)
[[gift_filters]]
supply_range = ["0", "inf"]         # Диапозон сапплая: [От, До]
price_range = ["0", "inf"]          # Диапозон цены:    [От, До]

# [[gift_filters]]
# supply_range = ["1001", "3000"]
# price_range = ["30001", "inf"]
